### ISSUE TITLE
RxAndroid?

### ISSUE THREAD

**Issue by agrosner** [germnix/acacia#2]
Just had a question...
Why does this library require/depend on RxAndroid? It adds a bunch of weight for this library for those who do not use it. If anything you should make it _explicitly_ clear in the README that this library depends on it for integration.

**Comment by ghost** [comment]
The dependency on RxAndroid is because the library can automatically subscribe Rx Observables to the worker thread, if the service uses them on the interface. 
Perhaps I can get rid of this required dependency by using Observable classes only if RxAndroid is already on the classpath.

**Comment by ghost** [comment]
Now in version 0.1.1 the required dependency on rx was removed, Acacia will only use it if the project already makes it available on the classpath.
